# Generated by Django 3.2.5 on 2021-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/post/covers/default.jpg', upload_to='post/covers'),
        ),
    ]
