# Generated by Django 3.2.5 on 2021-11-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/covers/default.jpg', upload_to='post/covers'),
        ),
    ]
